### getBlocksByChapterId
GET http://localhost:3013/api/v1/block/69383890ec0f8b3523b7997f
Content-Type: application/json

### create block with illustration
POST http://localhost:3013/api/v1/block/
Content-Type: application/json

{
  "chapterId": "69383890ec0f8b3523b7997f",
  "seq": 1,
  "contentType": "ILLUSTRATION",
  "content": "illustrationUrl.jpg"
}

### create block with sentence
POST http://localhost:3013/api/v1/block/
Content-Type: application/json

{
  "chapterId": "69383890ec0f8b3523b7997f",
  "seq": 1,
  "contentType": "SENTENCE",
  "content": [
    {
      "word": "I"
    },
    {
      "word": "ziehe",
      "lemma": "sich umziehen"
    },
    {
      "word": "mich",
      "refIndex": 1
    },
    {"word": "um", "refIndex": 1 },
    {"word":  ",", "punctuationMark": true },
    {"word":  "while"},
    {"word":  "Ich"},
    {"word":  "muss", "lemma":  "mussen"},
    {"word":  "zum"},
    {"word":  "Fitnessstudio"},
    {"word":  "gehen"}
  ],
  "character": "Emma",
  "avatarUrl": "avatarUrl.jpg",
  "avatarExpression": "SMILE",
  "balloonDirection": "LEFT",
  "balloonType": "THINK",
  "audio": "audio.mp3"
}

### create block only with a sentence
POST http://localhost:3013/api/v1/block/
Content-Type: application/json

{
  "chapterId": "69383890ec0f8b3523b7997f",
  "seq": 1,
  "contentType": "SENTENCE",
  "content": [
    {
      "word": "I"
    },
    {
      "word": "ziehe",
      "lemma": "sich umziehen"
    },
    {
      "word": "mich",
      "refIndex": 1
    },
    {"word": "um", "refIndex": 1 },
    {"word":  ",", "punctuationMark": true },
    {"word":  "while"},
    {"word":  "Ich"},
    {"word":  "muss", "lemma":  "mussen"},
    {"word":  "zum"},
    {"word":  "Fitnessstudio"},
    {"word":  "gehen"}
  ]
}

### update block by id
PUT http://localhost:3013/api/v1/block/693aa8f6f60fce35bdcc508b
Content-Type: application/json

{
  "seq": 0.001
}