### create story
POST http://localhost:3013/api/v1/story/
Content-Type: application/json

{
    "lang": "de-DE",
    "title": "nach Berlin",
    "note": "sein mit perfect",
    "tier": "free",
    "seq": 5,
    "level": "A1"
}

### create story - invalid request
POST http://localhost:3013/api/v1/story/
Content-Type: application/json

{
    "lang": "en-US",
    "title": "sd",
    "note": "sein mit perfect",
    "tier": "free",
    "seq": -0.1,
    "level": "Beginner"
}

### get stories by lang
GET http://localhost:3013/api/v1/story/lang/de-DE
Content-Type: application/json

### get stories by lang invalid language
GET http://localhost:3013/api/v1/story/lang/invalid-language
Content-Type: application/json

### update story
PUT http://localhost:3013/api/v1/story/6932f247beadbae643941736
Content-Type: application/json

{
    "lang": "de-DE",
    "title": "nach Berlin",
    "note": "sein mit perfect",
    "tier": "free",
    "seq": 10,
    "level": "A1"
}

### get stories with translations by langs
GET http://localhost:3013/api/v1/story/translations/lang-origin/de-DE/lang-target/en-US
Content-Type: application/json