### change-password
POST http://localhost:2013/api/v1/password-change
Content-Type: application/json

{
  "email": "malIN@emailegdss.com",
  "password1": "mY@passwords123",
  "password2": "mY@passwords123"
}