### create article
POST http://localhost:3013/article/
Content-Type: application/json

{
    "lang": "de",
    "title": "nach Berlin",
    "note": "sein mit perfect",
    "tier": "free",
    "seq": 5,
    "level": "A1"
}

### get article
GET http://localhost:3013/article/
Content-Type: application/json