### create many story locales
POST http://localhost:3013/story-locale
Content-Type: application/json

[
    {"storyId": "6932f6ff85cf673f3b380af7", "lang": "en-US", "titleTranslation":"english translation aaa"},
    {"storyId": "6932f6ff85cf673f3b380af7", "lang": "fr-FR", "titleTranslation":"french translation aaa"}
]

### getStoryLocalesByStoryId
GET http://localhost:3013/story-locale/6934a66b1299d755e3045b25
Content-Type: application/json